service: fiap-hackaton-auth

frameworkVersion: ^3.35.2

provider:
  name: aws
  runtime: nodejs18.x
  stage: v1
  region: us-east-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
          Resource: "*"
        - Effect: Allow
          Action:
            - cognito-idp:AdminSetUserPassword
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminGetUser
            - cognito-idp:ListUsers
            - cognito-idp:AdminInitiateAuth
            - cognito-idp:AdminRespondToAuthChallenge
            - cognito-idp:AdminConfirmSignUp
            - cognito-idp:AdminDeleteUser
          Resource: "arn:aws:cognito-idp:us-east-1:410211328905:userpool/us-east-1_PQCMQ5HXn"

functions:
  api:
    handler: dist/infrastructure/http/main.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY