name: Deploy Serverless AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checar repositório
        uses: actions/checkout@v2

      - name: Configura Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Instala dependências
        run: npm install --legacy-peer-deps

      - name: Instala jq para processamento JSON
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Executa testes com coverage
        run: npm run test:cov

      - name: Executa linting
        run: npm run lint

      - name: Exibe resultados dos testes
        run: |
          echo "=== RESUMO DOS TESTES ==="
          npm test -- --silent=false --verbose
          echo ""
          echo "=== COVERAGE SUMMARY ==="
          if [ -f "coverage/coverage-summary.json" ]; then
            cat coverage/coverage-summary.json | jq '.total'
          elif [ -f "coverage/lcov.info" ]; then
            echo "Coverage report gerado (lcov.info)"
            echo "Arquivos cobertos:"
            find coverage/lcov-report -name "*.html" -type f | head -10
          else
            echo "Coverage report não encontrado"
          fi



  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'

    steps:
      - name: Checar repositório
        uses: actions/checkout@v2

      - name: Configura Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Instala dependências
        run: npm install --legacy-peer-deps

      - name: Instala NestJS CLI globalmente
        run: npm install -g @nestjs/cli

      - name: Constrói o projeto com NestJS
        run: nest build

      - name: Configura AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy com Serverless Framework
        run: npx serverless deploy